version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./User.postman_collection.json
          environment: ./postman-test.postman_environment.json
workflows: null
